config/routes.rb
Rails.application.routes.draw do
  root to: "pages#home"
  patch "rentals/:id", to: "rentals#update", as: :rental
  devise_for :users
  resources :watches do
    resources :rentals, only: %i[new create]
  end
  # resources :rentals, only: %i[]
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  get "/dashboard", to: "pages#dashboard"
  get "/rental_requests", to: "pages#rental_requests"
  # Defines the root path route ("/")
  # root "articles#index"
  resources :brands
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/rental.rb
class Rental < ApplicationRecord
  belongs_to :watch
  belongs_to :user

  validates :start_date, presence: true
  validates :end_date, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  has_many :rentals
  has_many :watches, dependent: :destroy
  has_many :notifications
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/watch.rb
class Watch < ApplicationRecord
  has_many_attached :photos
  has_many :rentals, dependent: :destroy
  belongs_to :user

  include PgSearch::Model
  pg_search_scope :watch_search,
                  against: %i[name brand model],
                  using: {
                    tsearch: { prefix: true }
                  }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
    @user = current_user
    if current_user.nil?
      @watches = Watch.all
      if params[:query].present?
        @watches = @watches.watch_search(params[:query])
      end
    else
      @pick = []
      @watches = Watch.all
      if params[:query].present?
        @watches = @watches.watch_search(params[:query])
      end
      @watches.each do |watch|
        @pick << watch if watch.user_id != current_user.id
      end
    end
  end

  def dashboard
    @user = current_user
    @mywatches = current_user.watches
    @myrentals = current_user.rentals
    @notification_count = current_user.notification
  end

  def rental_requests
    @user = current_user
    @watches = @user.watches
  end
end

app/controllers/rentals_controller.rb
class RentalsController < ApplicationController
  def new
    @watch = Watch.find(params[:watch_id])
    @rental = Rental.new
  end

  def create
    @rental = Rental.new(rental_params)
    @watch = Watch.find(params[:watch_id])
    @rental.watch = @watch
    @rental.user = current_user
    @rental.status = "pending"
    watch_owner = @watch.user
    watch_owner.notification += 1
    if @rental.save
      redirect_to dashboard_path
    else
      render :new, status: :unprocessable_entity
    end
  end

  def update
    @rental = Rental.find(params[:id])
    @rental.status = (params[:rental][:status])
    current_user.notification -= 1
    @rental.save
    redirect_to rental_requests_path, status: :see_other
  end

  def destroy
    @watch = Watch.find(params[:id])
    @watch.destroy
    redirect_to rental_requests_path, status: :see_other
  end

  private

  def rental_params
    params.required(:rental).permit(:start_date, :end_date)
  end
end

app/controllers/watches_controller.rb
class WatchesController < ApplicationController

  before_action :set_watch, only: %i[edit update]

  def show
    @watch = Watch.find(params[:id])
    @rental = Rental.new
  end

  def new
    @watch = Watch.new
  end

  def toggle_available_status
    @available = false
    @available.toggle!(:enabled)
  end

  def create
    @watch = Watch.new(watch_params)
    @watch.user = current_user
    if @watch.save
      redirect_to watch_path(@watch)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def destroy
    @watch = Watch.find(params[:id])
    @watch.destroy
    redirect_to root_path, status: :see_other
  end

  def edit
  end

  def update
    if @watch.update(watch_params)
      redirect_to watch_path(@watch)
    else
      render :edit, status: :unprocessable_entity
    end
  end
end

private

def watch_params
  params.require(:watch).permit(:name, :model, :brand, :price, :description, photos: [])
end

def set_watch
  @watch = Watch.find(params[:id])
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/dashboard/dashboard.html.erb
<% @user.rentals.each do |rental| %>
  <%= rental.start_date %>
  <%= rental.end_date %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RentMyWatch</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.5.0/font/bootstrap-icons.css">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
    <style>
      html, body {
        height: 100%;
      }

      .wrapper {
        min-height: 100%;
        display: flex;
        flex-direction: column;
      }

      .content {
        flex-grow: 1;
      }
    </style>
  </head>

  <body>
    <div class="wrapper d-flex flex-column">
      <%= render "shared/navbar" %>

      <div class="content">
        <%= yield %>
      </div>

      <%= render "shared/footer" %>
    </div>
  </body>
</html>

app/views/pages/dashboard.html.erb
<div class="container p-5">
  <div class="py-5 text-center">
    <h1>Your Watch Collection</h1>
    <% if @mywatches.empty? %>
      <p>You have not rented a watch yet</p>
    <% else %>
      <div class="row justify-content-center">
        <% @mywatches.each do |watch| %>
          <div class="card col-3 text-center m-3">
            <%= render "shared/carousel", watch: watch %>
            <div class="card-body">
              <h5 class="fs-3"><%= watch.name %></h5>
              <%= watch.brand %> <%= watch.model %>
              <p class="card-text py-3"><%= watch.description[0, 50] %></p>
              <% if watch.rentals.any? %>
                  <p class="card-text py-3"><%= watch.rentals.last.start_date %> - <%= watch.rentals.last.end_date %></p>
                <% end %>
              <div class="btn btn-primary">
                <%= link_to "Show Me!", watch_path(watch), class: "text-white" %>
              </div>
            </div>
          </div>
        <% end %>
      </div>
    <% end %>
  </div>

  <div class="py-5 text-center">
    <h1>Your Rentals</h1>
    <% if @myrentals.empty? %>
      <P>You have not rented a watch yet</P>
    <% else %>
      <div class="row justify-content-center">
        <% @myrentals.each do |rental| %>
          <div class="card col-3 text-center m-3">
            <%= render "shared/carousel", watch: rental.watch %>
            <div class="card-body">
              <h5 class="fs-3"><%= rental.watch.name %></h5>
              <%= rental.watch.brand %> <%= rental.watch.model %>
              <p class="card-text py-3"><%= rental.watch.description[0, 50] %></p>
              <div class="btn btn-primary">
                <%= link_to "Show Me!", watch_path(rental.watch), class: "text-white" %>
              </div>
            </div>
          </div>
        <% end %>
      </div>
    <% end %>
  </div>
</div>

app/views/pages/home.html.erb
<h1 class ="text-center mt-5"><span data-controller="typed-js"></h1>
<div>
  <% if user_signed_in? %>
    <%if @pick.empty?%>
      <p class="text-center">There are no watches to rent</p>
    <%else%>
      <div class ="py-5">
        <div class="row justify-content-center">
          <% @pick.each do |watch| %>
            <div class="card col-3 text-center m-3">
              <%= render "shared/carousel", watch: watch %>
              <div class="card-body">
              <h5 class="fs-3"><%=watch.name%></h5>
              <%=watch.brand%> <%=watch.model%>
              <p class="card-text py-3"><%=watch.description[0, 50]%></p>
              <div class="btn btn-primary">
                <%= link_to "Show Me!", watch_path(watch), class: "text-white" %>
              </div>
              </div>
            </div>
          <% end %>
        </div>
      </div>
    <%end%>
  <% else %>
    <%if @watches.empty?%>
      <p class="text-center">There are no watches to rent</p>
    <%else%>
      <div class ="py-5">
        <div class="row justify-content-center">
          <% @watches.each do |watch| %>
            <div class="card col-3 text-center m-3">
              <%= render "shared/carousel", watch: watch %>
              <div class="card-body">
                <h5 class="fs-3"><%=watch.name%></h5>
                <%=watch.brand%> <%=watch.model%>
                <p class="card-text py-3"><%=watch.description[0, 50]%></p>
                <div class="btn btn-primary">
                  <%= link_to "Show Me!", watch_path(watch), class: "text-white" %>
                </div>
              </div>
            </div>
          <% end %>
        </div>
      </div>
    <%end%>
  <% end %>
</div>

app/views/pages/rental_requests.html.erb
<div class="container">
  <div class="row mb-5 py-3">
    <h1 class="text-center"><%= "You requests will appear here" %></h1>
    <div class="col">
    <% @watches.each do |watch| %>
      <% watch.rentals.each do |request| %>
        <div class="card-body rounded border bg-light">
          <% if request.status == 'pending' %>
            <div class="row px-5 py-3">
              <div class="col fw-bold"><p>User: <%= request.user.email %> has requested to rent your ad: <%= watch.name %>
                <p class="badge bg-warning text-dark"><%= request.status%></p></p></div>
                <div class="col-4">
                <%= link_to "Confirm", rental_path(request, rental: {status: 'confirmed'}), data: {"turbo-method": :patch}, class:"btn btn-primary btn-sm" %>
              <%= link_to "Decline", rental_path(request, rental: {status: 'declined'}), data: {"turbo-method": :patch}, class:"btn btn-secondary btn-sm" %>
            </div>
          <% end %>
        </div>
      <% end %>
    <% end %>
    </div>
  </div>
</div>

app/views/rentals/new.html.erb
<div class="container mt-5 mb-5 text-center d-flex flex-column border">
  <div class="row mt-5 mb-5">
    <div class="col-xl-12 col-lg-10 col-sm-offset-1">
      <h1>Rent this watch</h1>
      <h3><%= @watch.name %></h3>

      <%= simple_form_for [@watch, @rental] do |f| %>
        <%= f.input :start_date %>
        <%= f.input :end_date %>
        <%= f.submit class: 'btn btn-primary' %>
      <% end %>
    </div>
  </div>
</div>

app/views/shared/_carousel.html.erb
<div id="carouselExampleIndicators" class="carousel slide carousel-fade" data-bs-ride="carousel">
  <div class="carousel-indicators">
    <button type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide-to="0" class="active" aria-current="true" aria-label="Slide 1"></button>
    <button type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide-to="1" aria-label="Slide 2"></button>
    <button type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide-to="2" aria-label="Slide 3"></button>
  </div>
  <div class="carousel-inner">
    <% if watch.photos.present? %>
      <% watch.photos.each do |photo| %>
        <div class="carousel-item d-flex justify-content-center <%= "active" if photo == watch.photos.first %>">
          <%= cl_image_tag photo.key, height: 400, width: 400, crop: :fill, class:"d-block img-thumbnail my-5"%>
        </div>
      <%end%>
    <% else %>
      <div class="carousel-item d-flex justify-content-center active">
        <%= image_tag "default1.png", height: "400", width: "400", class:"d-block img-thumbnail my-5"%>
      </div>
    <% end %>
  </div>
  <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide="prev">
    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
    <span class="visually-hidden">Previous</span>
  </button>
  <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide="next">
    <span class="carousel-control-next-icon" aria-hidden="true"></span>
    <span class="visually-hidden">Next</span>
  </button>
</div>

app/views/shared/_footer.html.erb
<!-- Remove the container if you want to extend the Footer to full width. -->
<%# <footer class="absolute-bottom"> %>

  <!-- Footer -->
  <footer class="bg-dark text-center text-white">
    <!-- Grid container -->
    <div class="container p-4">
      <!-- Section: Social media -->
      <section class="mb-4">
        <!-- Facebook -->
        <a class="btn btn-outline-light btn-floating m-1" href="#!" role="button"
          ><i class="fab fa-facebook-f"></i
        ></a>

        <!-- Twitter -->
        <a class="btn btn-outline-light btn-floating m-1" href="#!" role="button"
          ><i class="fab fa-twitter"></i
        ></a>

        <!-- Google -->
        <a class="btn btn-outline-light btn-floating m-1" href="#!" role="button"
          ><i class="fab fa-google"></i
        ></a>

        <!-- Instagram -->
        <a class="btn btn-outline-light btn-floating m-1" href="#!" role="button"
          ><i class="fab fa-instagram"></i
        ></a>

        <!-- Linkedin -->
        <a class="btn btn-outline-light btn-floating m-1" href="#!" role="button"
          ><i class="fab fa-linkedin-in"></i
        ></a>

        <!-- Github -->
        <a class="btn btn-outline-light btn-floating m-1" href="#!" role="button"
          ><i class="fab fa-github"></i
        ></a>
      </section>
      <!-- Section: Social media -->

      <!-- Section: Form -->
      <section class="">
        <form action="">
          <!--Grid row-->
          <div class="row d-flex justify-content-center">
            <!--Grid column-->
            <div class="col-auto">
              <p class="pt-2">
                <strong>Sign up for our newsletter</strong>
              </p>
            </div>
            <!--Grid column-->

            <!--Grid column-->
            <div class="col-md-5 col-12">
              <!-- Email input -->
              <div class="form-outline form-white mb-4">
                <input type="email" id="form5Example2" class="form-control" placeholder="Email address"/>
              </div>
            </div>
            <!--Grid column-->

            <!--Grid column-->
            <div class="col-auto">
              <!-- Submit button -->
              <button type="submit" class="btn btn-outline-light mb-4">
                Subscribe
              </button>
            </div>
            <!--Grid column-->
          </div>
          <!--Grid row-->
        </form>
      </section>
      <!-- Section: Form -->

      <!-- Section: Text -->
      <!-- Section: Text -->

      <!-- Section: Links -->

    </div>
    <!-- Grid container -->

    <!-- Copyright -->
    <div class="text-center p-3" style="background-color: rgba(0, 0, 0, 0.2);">
      © 2020 Copyright:
      <a class="text-white" href="https://rendmywatch.com/">RendMyWatch.com</a>
    </div>
    <!-- Copyright -->
  </footer>
  <!-- Footer -->

<%# </footer> %>
<!-- End of .container -->

app/views/shared/_navbar.html.erb
<div class="navbar sticky-top navbar-expand-sm bg-dark navbar-lewagon text-white">
  <div class="container-fluid">
    <div>
      <%= link_to root_path, class: "navbar-brand" do %>
        <i class="bi bi-watch text-white ps-4" style="font-size: 25px"></i>
      <% end %>
      <%= link_to root_path, class: "navbar-brand ps-5" do %>
        <i class="fa-solid fa-house" style="color: #ffffff;"></i>
      <% end %>
    </div>

    <div class="row justify-content-center w-75">
      <div class="my-3">
        <%= form_with(url: root_path, method: :get, class: "d-flex") do |f| %>
          <%= f.text_field :query, class: "form-control", placeholder: "Type a keyword" %>
          <%= f.submit "Search", class: "btn btn-primary" %>
        <% end %>
      </div>
    </div>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
        <% if user_signed_in? %>
          <li class="nav-item dropdown">
            <a href="#" class="avatar" id="navbarDropdown" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              <%= image_tag "https://kitt.lewagon.com/placeholder/users/ssaunier", class: "avatar", alt: "dropdown menu" %>
            </a>
            <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
              <p class="fs-7 d-block p-2 text-dark"><%= current_user.email %></p>
              <%= link_to "Dashboard", dashboard_path, class: "dropdown-item border d-block p-2 bg-secondary text-white" %>
              <%= link_to "Notifications", rental_requests_path, class: (current_user.notification.zero? ? "dropdown-item border d-block p-2 bg-secondary text-white" : "dropdown-item bg-warning") %>
              <%= link_to "Offer new Watch", new_watch_path, class: "dropdown-item border d-block p-2 bg-secondary text-white" %>
              <%= link_to "Log out", destroy_user_session_path, data: { turbo_method: :delete }, class: "dropdown-item border d-block p-2 bg-secondary text-white" %>
            </div>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "Login", new_user_session_path, class: "nav-link text-light" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>

app/views/watches/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-xs-12 col-sm-10 col-sm-offset-1">
      <h1>Edit this watch</h1>
      <%= simple_form_for(@watch) do |f| %>
        <%= f.input :name %>
        <%= f.input :model %>
        <%= f.input :brand %>
        <%= f.input :description, as: :text %>
        <%= f.input :photos, as: :file, input_html: { multiple: true } %>
        <%= f.submit class: 'btn btn-primary mb-5' %>
      <% end %>
    </div>
  </div>
</div>

app/views/watches/new.html.erb
<div class="container mt-5">
  <div class="row justify-content-md-center">

      <h1 class="text-center">Create a new watch</h1>
      <%= simple_form_for @watch do |f| %>
        <%= f.input :name %>
        <%= f.input :model %>
        <%= f.input :brand %>
        <%= f.input :price %>
        <%= f.input :description, as: :text %>
        <%= f.input :photos, as: :file, input_html: { multiple: true } %>
        <%= f.submit class: 'btn btn-primary mb-5' %>
      <% end %>

  </div>
</div>

app/views/watches/show.html.erb
<div class="row bg-light">
  <div class="col-6 m-auto">
    <%= render "shared/carousel", watch: @watch %>
  </div>
  <div class="col-5 align-self-center rounded text-center pe-5 m-5">
    <h1><%= @watch.name %></h1>
    <h2><%= @watch.brand %> <%= @watch.model %></h2>
    <h2>Rent this watch for only <%= @watch.price %>,00€ a week</h2>
    <p><%= @watch.description %></p>
    <div class="btn-group" role="group" aria-label="Basic example">
      <% if current_user == @watch.user %>
        <%= link_to "Delete this Watch", watch_path(@watch), class:"btn btn-secondary btn-sm btn-danger", data: { turbo_method: :delete, turbo_confirm: "Are you sure you want to delete this list?" } %>
        <%= link_to "Edit this Watch", edit_watch_path(@watch), class:"btn btn-secondary btn-sm btn-secondary" %>
      <% end %>
      <button type="button" class="btn btn-secondary" data-bs-toggle="modal" data-bs-target="#exampleModal">Rent Me</button>
    </div>
  </div>
</div>
<!-- Modal -->
<div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h1 class="modal-title fs-5" id="exampleModalLabel">Modal title</h1>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
        <%= simple_form_for [@watch, @rental] do |f| %>
          <%= f.input :start_date, as: :date, html5: true %>
          <%= f.input :end_date, as: :date, html5: true %>
          <div class="modal-footer">
          <%= f.submit class: 'btn btn-primary' %>
        <% end %>
      </div>
      </div>
    </div>
  </div>
</div>